spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: otus

mongock:
  migrationScanPackage: ru.otus.hw.migrations
  enabled: true
logging:
  level:
    io.mongock: DEBUG
