spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: otus

mongock:
  enabled: true
  migration-scan-package: ru.otus.hw.migrations
logging:
  level:
    io.mongock: DEBUG
